---
deployment:
  tasks:
    - export DEPLOYPATH=/home/vibehyr/vibehyr.com
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R . $DEPLOYPATH
    - /usr/local/bin/npm install --prefix $DEPLOYPATH
    - /usr/local/bin/npm run build --prefix $DEPLOYPATH
